####  Section 1: Importing ####

# Importing data from an excel workbook
library(readxl)

# Get the original file path
getwd()

# Importing data

AWQP_Groundwater_Intermediate <- read_excel("02_Raw_Data/AWQP_Groundwater_CHECK.xlsx")


ECMC_Wells_Intermediate <- read_excel("02_Raw_Data/ECMC_Wells_CHECK.xlsx")
ECMC_Wells_Intermediate <- ECMC_Wells_Intermediate |>  filter(Units != "%")

NWQMC_Wells_Intermediate <- read_excel("02_Raw_Data/NWQMC_Wells_CHECK.xlsx")


#### Section 2: Merging ####

# Viewing the variables and data types

str(NWQMC_Wells_Intermediate)
length(NWQMC_Wells_Intermediate)
unique(NWQMC_Wells_Intermediate)

str(AWQP_Groundwater_Intermediate)
length(AWQP_Groundwater_Intermediate)
unique(AWQP_Groundwater_Intermediate)

str(ECMC_Wells_Intermediate)
length(ECMC_Wells_Intermediate)
unique(ECMC_Wells_Intermediate)


# Converting datatypes so they match for the merge

AWQP_Groundwater_Intermediate$Qualifier <- as.character(AWQP_Groundwater_Intermediate$Qualifier)
AWQP_Groundwater_Intermediate$Date <- as.Date(AWQP_Groundwater_Intermediate$Date)

NWQMC_Wells_Intermediate$Result <- as.numeric(NWQMC_Wells_Intermediate$Result)
NWQMC_Wells_Intermediate$Date <- as.Date(NWQMC_Wells_Intermediate$Date)

ECMC_Wells_Intermediate$SampleID <- as.character(ECMC_Wells_Intermediate$SampleID)


# Merging using bind_rows
GW_Merged <- bind_rows(ECMC_Wells_Intermediate, AWQP_Groundwater_Intermediate)


GW_Merged2 <- bind_rows (GW_Merged, NWQMC_Wells_Intermediate)

# Reordering columns
GW_Merged3 <- GW_Merged2 |>  select(
  Source,
  Media,
  SiteType,
  PrimaryUsage,
  Date,
  SampleID,
  Analyte,
  AnalyteType,
  Result,
  Units,
  Qualifier,
  NonDetect,
  DetectionLimit,
  MonitoringRegion,
  Longitude,
  Latitude,
  SiteID,
  everything()
)


unique(GW_Merged3$PrimaryUsage)



####  Cleaning data - renaming variables, condensing variables, adding values when NA #####

# Creating a unique identifier for each row
GW_Merged3$Unique_ID <- 1:nrow(GW_Merged3)


#### Categorizing analytes ####

Physical_Parameters <- c("WATER",
  "RESISTIVITY",
  "PH Electrometric Method",
  "Total solids",
  "Total suspended solids",
  "Chemical oxygen demand, (high level)",
  "Chemical oxygen demand, (low level)",
  "Alkalinity, bicarbonate",
  "Hardness, carbonate",
  "Alkalinity, total",
  "Alkalinity, carbonate",
  "Age",
  "CARBONATE ALKALINITY AS CACO3",
  "pH, FIELD",
  "PH, LAB",
  "DISSOLVED OXYGEN",
  "OIL AND GREASE",
  "SODIUM ADSORPTION RATIO",
  "COLOR",
  "SALINITY",
  "Phen ALKALINITY AS CACO3",
  "Temperature of pH determination",
  "% SOLIDS",
  "TOTAL SOLIDS",
  "PARAFFIN CONTENT",
  "SUM OF CATIONS",
  "ELECTRICAL CONDUCTIVITY @ SATURATION",
  "% MOISTURE",
  "HARDNESS AS CA",
  "BIOCHEMICAL OXYGEN DEMAND (BOD5)",
  "Field Alkalinity",
  "ORP - Oxidation-Reduction Potential",
  "Turb - Turbidity",
  "TDS (Lab) - Total Dissolved Solids (Lab)",
  "TDS (Field) - Total Dissolved Solids (Field)",
  "WaterT - Water Temperature",
  "AirT - Air Temperature",
  "ECs (Field) - Specific Conductance (Field)",
  "ECs (Lab) - Specific Conductance (Lab)",
  "SWL - Static Water Level",
  "Sal - Salinity (Field)",
  "pH (Field) - pH (Field)",
  "pH (Lab) - pH (Lab)",
  "Hardness_CaCO3 - Hardness (CaCO3)",
  "Specific conductance",
  "Total dissolved solids",
  "Total Depth",
  "pH",
  "Hardness, non-carbonate",
  "Specific conductance",
  "CARBONATE ALKALINITY AS CACO3",
  "pH, FIELD",
  "pH, LAB",
  "DISSOLVED OXYGEN",
  "Specific Conductivity",
  "SPECIFIC CONDUCTIVITY",
  "Specific Conductivity, Field",
  "SPECIFIC CONDUCTIVITY, FIELD",
  "Turbidity",
  "TURBIDITY",
  "Turbidity, Field",
  "TURBIDITY, FIELD",
  "Temperature",
  "TEMPERATURE",
  "Temperature, Field",
  "TEMPERATURE, FIELD",
  "pH, Field",
  "pH, LAB",
  "pH Electrometric Method",
  "Acidity, (H+)",
  "Alkalinity",
  "ALKALINITY",
  "Alkalinity, Total",
  "TOTAL ALKALINITY AS CACO3",
  "Alkalinity, Bicarbonate",
  "Alkalinity, Carbonate",
  "Alkalinity, Hydroxide",
  "Alkalinity as CaCO3",
  "Alkalinity, Total as CaCO3",
  "Carbonate Alkalinity as CaCO3",
  "BICARBONATE ALKALINITY as CACO3",
  "HYDROXIDE ALKALINITY AS CACO3",
  "Phen Alkalinity as CaCO3",
  "Hardness (as CaCO3)",
  "HARDNESS (AS CACO3)",
  "Hardness, Total",
  "HARDNESS, TOTAL",
  "Hardness, Non-Carbonate",
  "Hardness, Carbonate",
  "Calcium Hardness",
  "CALCIUM HARDNESS",
  "Total Dissolved Solids",
  "TOTAL DISSOLVED SOLIDS",
  "Total Dissolved Solids, Calculated Field",
  "TOTAL DISSOLVED SOLIDS, CALCULATED FIELD",
  "Total Dissolved Solids, Calculated Lab",
  "TOTAL DISSOLVED SOLIDS, CALCULATED LAB",
  "Total Dissolved Solids, Calculated",
  "Resistivity",
  "Specific Gravity",
  "SPECIFIC GRAVITY",
  "Salinity",
  "Oil and Grease",
  "HEM (Oil and Grease)",
  "Settleable solids",
  "Total Suspended Solids",
  "TOTAL SUSPENDED SOLIDS",
  "Total Solids",
  "TOTAL SOLIDST",
  "Color",
  "COLORS",
  "Density of water at 20 deg C",
  "% Solids",
  "% Moisture",
  "Chemical Oxygen Demand",
  "CHEMICAL OXYGEN DEMAND",
  "Chemical Oxygen Demand (high level)",
  "Chemical Oxygen Demand (low level)",
  "Biochemical Oxygen Demand (BOD5)",
  "Biochemical Oxygen Demand, standard conditions",
  "Biochemical oxygen demand, standard conditions",
  "Total Organic Carbon",
  "DISSOLVED ORGANIC CARBON",
  "Methylene blue active substances",
  "MBAS (mol.wt 320)",
  "Methane, Field",
  "METHANE, FIELD",
  "Hydrogen Sulfide, Field",
  "HYDROGEN SULFIDE, FIELD",
  "Oxidation Reduction Potential",
  "OXIDATION REDUCTION POTENTIAL",
  "Oxidation Reduction Potential, Field",
  "OXIDATION REDUCTION POTENTIAL, FIELD",
  "Dissolved Oxygen, Field",
  "DISSOLVED OXYGEN, FIELD",
  "Dissolved Oxygen",
  "DISSOLVED OXYGENT",
  "Dissolved Oxygen - Saturation %",
  "DISSOLVED OXYGEN - SATURATION %",
  "DO (mg/L)",
  "DO_mgL - DO (mg/L)",
  "Total Residual Chlorine",
  "Total Recoverable Petroleum Hydrocarbons",
  "TOTAL RECOVERABLE PETROLEUM HYDROCARBONS",
  "Total Purgeable Hydrocarbons",
  "TOTAL PURGEABLE HYDROCARBONS",
  "Water",
  "Cation-Anion Balance",
  "CATION - ANION BALANCE",
  "Sum of Anions",
  "SUM OF ANIONS",
  "Sum of Cations",
  "SUM OF CATIONST",
  "Percent difference",
  "TDS, Measured to Calculated Ratio",
  "TDS, MEASURED TO CALCULATED RATIO",
  "MEASURED H2O FLOW",
  "MEASURED GAS FLOW",
  "VOLUME PURGED",
  "TOTAL DEPTH",
  "GROUNDWATER ELEVATION (MSL)",
  "MEASURED FLOW",
  "DEPTH TO WATER",
  "PURGE RATE",
  "Foaming Agents"
)












Gases <- c("Sulfur Dioxide",
  "HYDROGEN CYANIDE",
  "SULFIDE as H2S",
  "SULFUR DIOXIDE",
  "Sulfur hexafluoride",
  "CFC-11",
  "CFC-12",
  "CFC-113",
  "Carbon monoxide",
  "Propylene",
  "Ethane",
  "Ethylene",
  "222Radon",
  "AIR",
  "SULFUR DIOXIDE",
  "OXYGEN/ARGON RATIO",
  "OXYGEN + ARGON",
  "Hydrogen sulfide",
  "Carbon dioxide",
  "Helium-4",
  "HCFC-22",
  "HFC-152a",
  "CFC-114",
  "HCFC-123",
  "Ethane, 1-chloro-1,1-difluoro-",
  "Oxygen",
  "Carbon dioxide",
  "Methane",
  "METHANE",
  "Hydrogen Sulfide",
  "HYDROGEN SULFIDE",
  "Argon",
  "ARGON",
  "British Thermal Units",
  "BRITISH THERMAL UNITS",
  "Carbon Monoxide",
  "CARBON MONOXIDE",
  "Carbon Dioxide",
  "CARBON DIOXIDE",
  "Ethene",
  "ETHENE",
  "Helium",
  "HELIUM",
  "Hydrogen",
  "HYDROGEN",
  "Isobutane",
  "ISOBUTANE",
  "Isopentane",
  "ISOPENTANE",
  "Butane",
  "BUTANE",
  "Nitrogen (N2)",
  "NITROGEN (N2)",
  "Pentane",
  "PENTANE",
  "Oxygen (O2)",
  "OXYGEN (O2)",
  "Propane",
  "PROPANE",
  "Propene",
  "PROPENE",
  "C6+ (hexanes +)",
  "C6+ (hexanes +)",
  "Acetylene",
  "Ethylene",
  "Ethylene",
  "British Thermal Units-Dry Basis",
  "BRITISH THERMAL UNITS- DRY BASIS",
  "% Combustible Gas",
  "% COMBUSTIBLE GAS",
  "Nitrogen",
  "NEODYMIUM",
  "Neon",
  "NEON",
  "Xenon",
  "XENON",
  "Krypton",
  "KRYPTON",
  "Helium-3/helium-4 ratio",
  "HELIUM-3/HELIUM-4 RATIO",
  "Neon-20/Neon-22 ratio",
  "NEON-20/NEON-22 RATIO",
  "Argon-40/Argon-36 ratio",
  "ARGON-40/ARGON-36 RATIO",
  "Krypton-86/Krypton-84 ratio",
  "KRYPTON-86/KRYPTON-84 RATIO",
  "Xenon-130/Xenon-132 ratio",
  "XENON-130/XENON-132 RATIO",
  "Helium-3/helium-4 error",
  "HELIUM-3/HELIUM-4 ERROR",
  "Neon-20/Neon-22 error",
  "NEON-20/NEON-22 ERROR",
  "Argon-40/Argon-36 error",
  "ARGON-40/ARGON-36 ERROR",
  "Krypton-86/Krypton-84 error",
  "KRYPTON-86/KRYPTON-84 ERROR",
  "Xenon-130/Xenon-132 error",
  "XENON-130/XENON-132 ERROR",
  "Partial pressure of dissolved gases"
)




VOCs <- c("1,2,3-Trimethylbenzene",
  "1,2,3-TRIMETHYLBENZENE",
  "m-XYLENE",
  "TOLUENE MONOOXYGENASE FUNCTIONAL GENE",
  "BENZYL SUCCINATE SYNTHASE FUNCTIONAL GENES",
  "TBA MONOOXYGENASE FUNCTIONAL GENE",
  "Soluble Methane Monoxygenase Functional Gene",
  "tert-Amyl methyl ether",
  "n-Butylbenzene",
  "Acrylonitrile",
  "Methacrylonitrile",
  "Methyl methacrylate",
  "Ethyl methacrylate",
  "Tetrahydrofuran",
  "2-Chloroethyl vinyl ether",
  "Acrolein",
  "sec-Butyl acetate",
  "Toluene-d8",
  "1,2-Dichloroethane-d4",
  "Hexachloroethane",
  "1,3-Dichlorobenzene",
  "1,2,3,4-Tetramethylbenzene",
  "trans-1,4-Dichloro-2-butene",
  "Hexachlorocyclopentadiene",
  "Tetrahydrofuran-d8",
  "1-Bromo-3-chloropropane-d6",
  "Trihalomethanes",
  "1,1,2,2-Tetrachloroethane",
  "Hexachlorobutadiene",
  "Methyl Acrylate",
  "1,2,3,5-Tetramethylbenzene",
  "Vinyl bromide",
  "Ethyl tert-butyl ether",
  "1,1-Dichloropropene",
  "2,2-Dichloropropane",
  "1,3-Dichloropropane",
  "o-Ethyltoluene",
  "Cumene",
  "1,3,5-Trimethylbenzene",
  "o-Chlorotoluene",
  "p-Chlorotoluene",
  "tert-Butylbenzene",
  "p-Cymene",
  "Methyl iodide",
  "1,2,3-Trichlorobenzene",
  "Allyl chloride",
  "Methyl isobutyl ketone",
  "Acetone",
  "Bromobenzene",
  "Ethyl ether",
  "Isopropyl ether",
  "Methyl ethyl ketone",
  "2-Methylbutane",
  "Xylene",
  "Vinyl acetate",
  "1,3-Dichloropropene",
  "1,2-Dibromoethylene",
  "M-+P-XYLENE",
  "TEPH DIESEL RANGE ORGANICS",
  "1,3-DICHLOROBENZENE",
  "N-BUTYLBENZENE",
  "ACROLEIN",
  "ACRYLONITRILE",
  "2-CHLOROETHYL VINYL ETHER",
  "cis-1,4-DICHLORO-2-BUTENE",
  "PENTACHLOROETHANE",
  "PROPIONITRILE",
  "tert-AMYL METHYL ETHER",
  "TETRAHYDROFURAN",
  "trans-1,4-DICHLORO-2-BUTENE",
  "1,2,4-TRICHLOROBENZENE (S)",
  "BTEX",
  "ETHANOL",
  "N-Butanol",
  "CYCLOHEXANE",
  "CYCLOHEXANONE",
  "ISOPHORONE",
  "HEXACHLOROPROPENE",
  "DIALLATE",
  "ACETALDEHYDE",
  "isovaleraldehyde",
  "1-Propanol",
  "2-butanol",
  "1,2,3,4-TETRAMETHYLBENZENE",
  "2-BROMOCHLOROBENZENE",
  "NITROBENZENE-d5",
  "N-HEXANE",
  "1-NONANAL",
  "OCTANE, MIXED ISOMERS",
  "n-octane",
  "1,2-Dichlorobenzene-D4",
  "DIBROMOFLUOROMETHANE",
  "2-Methoxyethanol",
  "2-(2-Butoxyethoxy)ethanol",
  "2-propoxyethanol",
  "4-HYDROXY-4-METHYL-2-PENTANONE",
  "DIPROPYLENE GLYCOL METHYL ETHER",
  "2-Ethoxylethyl acetate",
  "2-Nitropropane",
  "2-PENTANONE",
  "Ethyl acetate",
  "Isoamyl acetate",
  "Isobutyl acetate",
  "Isopropyl acetate",
  "n-Butyl acetate",
  "n-Propyl acetate",
  "Flourobenzene",
  "2-CHLOROPROPANE",
  "TIC-Unknown1",
  "TIC-Unknown2",
  "TIC-Unknown3",
  "TIC-Unknown4",
  "Hexachloropropene",
  "TEPH MOTOR OIL RANGE ORGANICS",
  "METHANOL",
  "TRIHALOMETHANES (THM)",
  "TOLUENE-D8",
  "1,2-DICHLOROETHANE-d4",
  "1,2-Dichloroethane",
  "Tribromomethane",
  "1,1,2-Trichloroethane",
  "1,1-Dichloroethane",
  "1,1-Dichloroethene",
  "1,1,1-Trichloroethane",
  "o-Dichlorobenzene",
  "1,2-Dichloropropane",
  "trans-1,2-Dichloroethylene",
  "1,2,4-Trichlorobenzene",
  "p-Dichlorobenzene",
  "trans-1,3-Dichloropropene",
  "cis-1,3-Dichloropropene",
  "Propyl acetate",
  "Isobutyl alcohol-d6",
  "1,3-Butadiene",
  "Ethylene glycol monoethyl ether acetate",
  "2-Propen-1-ol",
  ".alpha.-Terpineol",
  "Butyraldehyde",
  "trans-Crotonaldehyde",
  "Isopropanol",
  "Methyl acetate",
  "1-Butanol",
  "tert-Butanol",
  "Carbon disulfide",
  "Pentanal",
  "cis-1,2-Dichloroethylene",
  "4-Methyl-2-pentanol",
  "Styrene",
  "o-Xylene",
  "Methyl isoamyl ketone",
  "1,2,4-Trimethylbenzene",
  "n-Propylbenzene",
  "Bromochloromethane",
  "1-Octanol",
  "2-Ethylhexanol",
  "1,2,3,4-Tetrahydronaphthalene",
  "sec-Butylbenzene",
  "2,6-Dimethyl-4-heptanone",
  "1,2,3-Trichloropropane",
  "Chloropicrin",
  "1,1,1,2-Tetrachloroethane",
  "Ethylene dibromide",
  "Methyl tert-butyl ether",
  "1,1-Dichloropropanone",
  "Dimethoxymethane",
  "1,4-Dioxane",
  "1,3-Dioxolane",
  "Hexane",
  "1,2-Dibromo-3-chloropropane",
  "m,p-Xylene",
  "Acetochlor-d11",
  "Alachlor-d13",
  "Carbaryl-d7",
  "Carbendazim-d4",
  "2-METHYL-2-BUTANOL",
  "ETHYL METHACRYLATE",
  "METHACRYLONITRILE",
  "METHYL METHACRYLATE",
  "TOLUENE-D8",
  "1,2,4,5-TETRACHLOROBENZENE",
  "N-NITROSODIETHYLAMINE",
  "N-NITROSOMETHYLETHYLAMINE",
  "M-P-XYLENE",
  "o-XYLENE",
  "O-XYLENE",
  "BENZENE",
  "METHYL-tert-BUTYL-ETHER (MTBE)",
  "TOLUENE",
  "ACETONE",
  "ETHYLBENZENE",
  "HEXANES",
  "ISOBUTANE",
  "ISOPENTANE",
  "BUTANE",
  "PENTANE",
  "PROPANE",
  "TOTAL XYLENES",
  "ETHANE",
  "1,1,1,2-TETRACHLOROETHANE",
  "1,1,1-TRICHLOROETHANE",
  "1,1,2,2-TETRACHLOROETHANE",
  "1,1,2-TRICHLORO-1,2,2-TRIFLUOROETHANE",
  "1,1,2-TRICHLOROETHANE",
  "1,1-DICHLOROETHANE",
  "1,1-DICHLOROETHENE",
  "1,1-DICHLOROPROPENE",
  "1,2,3-TRICHLOROBENZENE",
  "1,2,3-TRICHLOROPROPANE",
  "1,2,4-TRICHLOROBENZENE",
  "1,2,4-TRIMETHYLBENZENE",
  "1,2-DIBROMO-3-CHLOROPROPANE",
  "1,2-DIBROMOETHANE",
  "1,2-DICHLOROBENZENE",
  "1,2-DICHLOROETHANE",
  "1,2-DICHLOROPROPANE",
  "1,3,5-TRIMETHYLBENZENE",
  "1,3-DICHLOROPROPANE",
  "1,4-DICHLOROBENZENE",
  "1-CHLOROHEXANE",
  "2,2-DICHLOROPROPANE",
  "2-BUTANONE",
  "2-CHLOROTOLUENE",
  "2-HEXANONE",
  "4-CHLOROTOLUENE",
  "4-ISOPROPYLTOLUENE",
  "4-METHYL-2-PENTANONE",
  "BROMOBENZENE",
  "BROMOCHLOROMETHANE",
  "BROMODICHLOROMETHANE",
  "BROMOFORM",
  "BROMOMETHANE",
  "CARBON DISULFIDE",
  "CARBON TETRACHLORIDE",
  "CHLOROBENZENE",
  "CHLOROETHANE",
  "CHLOROFORM",
  "CHLOROMETHANE",
  "cis-1,2-DICHLOROETHENE",
  "cis-1,3-DICHLOROPROPENE",
  "DIBROMOCHLOROMETHANE",
  "DIBROMOMETHANE",
  "DICHLORODIFLUOROMETHANE",
  "DICHLOROMETHANE (methylene chloride)",
  "HEXACHLORO-1,3-BUTADIENE",
  "IODOMETHANE",
  "ISOPROPYLBENZENE",
  "n-BUTYLBENZENE",
  "n-PROPYLBENZENE",
  "sec-BUTYLBENZENE",
  "STYRENE",
  "tert-BUTYLBENZENE",
  "TETRACHLOROETHENE",
  "trans-1,2-DICHLOROETHENE",
  "trans-1,3-DICHLOROPROPENE",
  "TRICHLOROETHENE",
  "TRICHLOROFLUOROMETHANE",
  "VINYL ACETATE",
  "VINYL CHLORIDE",
  "2-PROPANOL",
  "1,4-DIOXANE",
  "2-BUTOXYETHANOL",
  "ACETONITRILE",
  "ALLYL CHLORIDE",
  "CHLOROPRENE",
  "ETHER",
  "ETHYL tert-BUTYL ETHER",
  "ISOBUTYL ALCOHOL",
  "ISOPROPYL ETHER",
  "METHYL ACETATE",
  "METHYL CYCLOHEXANE",
  "n-BUTANOL",
  "tert-BUTANOL",
  "1,3-BUTADIENE",
  "1,2-DICHLOROETHENE (SUM OF ISOMERS)",
  "Diethylene Glycol",
  "Ethylene Glycol",
  "Hexanal",
  "Octanal",
  "Propylene Glycol",
  "Tetramethylene Glycol",
  "Triethylene Glycol",
  "Methanol",
  "Cyclohexane",
  "Cyclohexanone",
  "Diethyl Ether",
  "2-Hexanone",
  "Vinyl Acetate",
  "Benzotrifluoride",
  "Total Purgeable Hydrocarbons",
  "TOTAL PURGEABLE HYDROCARBONS",
  "1-CHLOROHEXANE",
  "1,3-DICHLOROPROPENE (SUM OF ISOMERS)",
  "o-XYLENE",
  "m,p-XYLENE",
  "N-NITROSO-di-n-PROPYLAMINEN-NITROSODIPHENYLAMINE",
  "Dichlorobromomethane",
  "DICHLOROBROMOMETHANE",
  "Chlorodibromomethane",
  "CHLORODIBROMOMETHANE",
  "Toluene",
  "TOLUENE",
  "Benzene",
  "BENZENE",
  "Chlorobenzene",
  "CHLOROBENZENE",
  "Ethylbenzene",
  "ETHYLBENZENE",
  "Naphthalene",
  "NAPHTHALENE",
  "Vinyl chloride",
  "VINYL CHLORIDE",
  "Chloroform",
  "CHLOROFORM",
  "Methylene chloride",
  "METHYLENE CHLORIDE",
  "Carbon tetrachloride",
  "CARBON TETRACHLORIDE",
  "Trichloroethylene",
  "TRICHLOROETHYLENE",
  "Tetrachloroethylene",
  "TETRACHLOROETHYLENE",
  "Chloromethane",
  "CHLOROMETHANE",
  "Chloroethane",
  "CHLOROETHANE",
  "Methyl bromide",
  "METHYL BROMIDE",
  "Dibromomethane",
  "DIBROMOMETHANE"
)








PAHs <- c(
  "Anthracene",
  "Benzo[a]pyrene",
  "Fluoranthene",
  "Phenanthrene",
  "Pyrene",
  "1-Methylnaphthalene",
  "2,6-Dimethylnaphthalene",
  "2-Methylnaphthalene",
  "Acenaphthylene",
  "Acenaphthene",
  "Benzo(b)fluoranthene",
  "Benzo[k]fluoranthene",
  "Chrysene",
  "Fluorene",
  "Indeno[1,2,3-cd]pyrene",
  "Benzo[ghi]perylene",
  "Benz[a]anthracene",
  "Dibenz[a,h]anthracene",
  "2-CHLORONAPHTHALENE",
  "DIBENZ(A,H)ACRIDINE",
  "N-(1-NAPHTHYL)ETHYLENEDIAMINE DIHYDROCHLORIDE",
  "BENZO (B + K ) FLUORANTHENE",
  "DIBENZ(A,J)ACRIDINE",
  "7,12-DIMETHYLBENZ(A)ANTHRACENE",
  "1,1'-Biphenyl",
  "PYRENE",
  "1-METHYLNAPHTHALENE",
  "2-METHYLNAPHTHALENE",
  "ACENAPHTHENE",
  "ACENAPHTHYLENE",
  "ANTHRACENE",
  "BENZ(a)ANTHRACENE",
  "BENZO(a)PYRENE",
  "BENZO(b)FLUORANTHENE",
  "BENZO(ghi)PERYLENE",
  "BENZO(k)FLUORANTHENE",
  "CHRYSENE",
  "DIBENZ(a,h)ANTHRACENE",
  "FLUORANTHENE",
  "FLUORENE",
  "INDENO(1,2,3-cd)PYRENE",
  "NAPHTHALENE",
  "PHENANTHRENE",
  "BENZO[GHI]FLUORANTHENE",
  "BENZO[A]PYRENE",
  "DIBENZ[A,H]ANTHRACENE",
  "BENZO(B + K ) FLUORANTHENE",
  "BENZO[K]FLUORANTHENE",
  "1-CHLORONAPHTHALENE",
  "1,2-DIPHENYLHYDRAZINE"
)








Fuels_Hydrocarbon_Mixtures <- c(
  "C8+",
  "Hydrocarbons, C6 and higher-molecular-weight",
  "TOTAL PETROLEUM HYDROCARBONS (sum of TVPH and TEPH)",
  "TVPH - Gasoline Range Organics",
  "TEPH Diesel Range Organics",
  "Total Petroleum Hydrocarbons (sum of TVPH and TEPH)",
  "TEPH Diesel Range Organics (extended)",
  "TEPH Motor Oil Range Organics",
  "Total Recoverable Petroleum Hydrocarbons",
  "C10-C28 Diesel Range Organics",
  "C28-C40 Oil Range Organics",
  "TNRCC 1005 C12 to C28 fraction",
  "TNRCC 1005 C28-C35 fraction",
  "TNRCC 1005 C6 to C12 fraction",
  "TNRCC 1005 TPH sum of fractions"
)



Other_Organics <- c("Disulfoton","Total Coliform",
  "BACTERIA, IRON RELATED",
  "BACTERIA, SLIME FORMING",
  "BACTERIA, SULFATE REDUCING",
  "BACTERIA, TOTAL COLIFORM",
  "BACTERIA, FECAL COLIFORM",
  "Bacteria, Fecal + Total Coliform",
  "BACTERIA, E COLI",
  "Sulfate Reducing Bacteria Functional Gene DNA Expression",
  "Methanogen Phylogenetic Group DNA Expression",
  "Methane Oxidizing Bacteria Phylogenetic Group DNA Expression",
  "3-METHYLCHOLANTHRENE",
  "alpha-BHC",
  "4-BROMOFLUOROBENZENE",
  "2-FLUOROBIPHENYL",
  "TERPHENYL-d14",
  "3-+4-METHYLPHENOL",
  "SULFITE",
  "DISULFOTON",
  "Total CYANIDE",
  "2,4,5-TP",
  "3-Hydroxycarbofuran",
  "Aldicarb",
  "Aldicarb sulfoxide",
  "Aldrin",
  "Carbaryl",
  "Carbofuran",
  "Chlorothalonil",
  "Cyanazine",
  "Diazinon",
  "Dieldrin",
  "Endrin",
  "Glyphosate",
  "Heptachlor",
  "Heptachlor epoxide",
  "Methiocarb",
  "Methoxychlor",
  "Oxamyl",
  "Phorate",
  "Propachlor",
  "Propoxur",
  "Trifluralin",
  "Atrazine",
  "Metolachlor",
  "Dicamba",
  "Picloram",
  "Hexazinone",
  "Metribuzin",
  "Simazine",
  "Aldicarb sulfone",
  "Chlorpyrifos",
  "Methomyl",
  "Methyl parathion",
  "Pronamide",
  "Halosulfuron-methyl",
  "Desisopropyl atrazine",
  "Fenamiphos Sulfone",
  "Chlorimuron-ethyl",
  "HCFC-21",
  "N-Nitrosodiethylamine",
  "3-Phenoxybenzoic acid-13C6",
  "Endosulfan sulfate",
  "Dinoseb",
  "Pentachlorophenol",
  "Phenol",
  "Carbazole",
  "2-Methyl-2-butanol",
  "Chlordane, technical",
  "Toxaphene",
  "Aroclor 1221",
  "Aroclor 1232",
  "Aroclor 1254",
  "Aroclor 1260",
  "Butachlor",
  "Bis(2-chloroethoxy)methane",
  "N-Nitrosodiphenylamine",
  "N-Nitrosodimethylamine",
  "2-Chloronaphthalene",
  "2,4-Dichlorophenol",
  "2,4-Dimethylphenol",
  "2,4-Dinitrotoluene",
  "2,4-Dinitrophenol",
  "2,4,6-Trichlorophenol",
  "2,6-Dinitrotoluene",
  "Hexachlorobenzene",
  "Endrin aldehyde",
  "3,3'-Dichlorobenzidine",
  "2,4,5-Trichlorophenol",
  "MBAS",
  "Bromide",
  "Carbofuran-D3",
  "Deethylatrazine-d6",
  "Diflubenzuron-d4",
  "Hexazinone-d6",
  "Linuron-d6",
  "Malathion-D10",
  "Metolachlor-d6",
  "Nicosulfuron-d6",
  "Tebuconazole-d6",
  "Thiobencarb-d10",
  "cis-Permethrin-13C6",
  "Butachlor ESA",
  "Dimethachlor sulfonic acid",
  "p-Bromofluorobenzene",
  "Diuron-d6",
  "2,4-D-d3",
  "Norethisterone",
  "Acetaminophen",
  "Albuterol",
  "Bupropion",
  "Carbamazepine",
  "Cimetidine",
  "Codeine",
  "Cotinine",
  "Dehydronifedipine",
  "1,7-Dimethylxanthine",
  "Ethanamine, 2-(diphenylmethoxy)-N,N-dimethyl-",
  "Duloxetine",
  "Erythromycin",
  "Fluoxetine",
  "Norfluoxetine",
  "Ranitidine",
  "Sulfamethoxazole",
  "Thiabendazole",
  "Trimethoprim",
  "Warfarin",
  "Morphine",
  "Hydrocortisone",
  "Pseudoephedrine/Ephedrine mix",
  "Amphetamine",
  "Acetamide, 2-(diethylamino)-N-(2,6-dimethylphenyl)-",
  "Meprobamate",
  "Metoprolol",
  "Dilantin",
  "Prednisone",
  "Dextromethorphan",
  "Temazepam",
  "Verapamil",
  "Triamterene",
  "Sulfamethizole",
  "Antipyrine",
  "Fluconazole",
  "Nizatidine",
  "Pentoxifylline",
  "Iminostilbene",
  "Prednisolone",
  "Acyclovir",
  "Betamethasone",
  "Ezetimibe",
  "Loratadine",
  "Fenofibrate",
  "Metformin",
  "Nicotine",
  "Theophylline",
  "Morphinan-6-one, 4,5-epoxy-14-hydroxy-3-methoxy-17-methyl-, (5.alpha.)-",
  "Phendimetrazine",
  "Chlorpheniramine",
  "Carisoprodol",
  "Diazepam",
  "Methadone",
  "Methocarbamol",
  "Atenolol",
  "Sulfadimethoxine",
  "Metaxalone",
  "Citalopram",
  "Hydrocodone",
  "Valacyclovir",
  "Tiotropium",
  "Fexofenadine",
  "Oseltamivir",
  "Omeprazole/Esomeprazole mix",
  "Tolyl triazole",
  "Loperamide",
  "Propranol",
  "Tramadol",
  "Clonidine",
  "Diltiazem",
  "Fluvoxamine",
  "Amitriptyline",
  "Promethazine",
  "Methotrexate",
  "Paroxetine",
  "Sertraline",
  "Fluticasone propionate",
  "Raloxifene",
  "Sitagliptin",
  "Norsertraline",
  "Venlafaxine",
  "Hydroxy-amitriptyline, 10-",
  "Benztropine",
  "Desmethyldiltiazem",
  "Famotidine",
  "Glipizide",
  "Glyburide",
  "Hydroxyzine",
  "Nadolol",
  "Norverapamil",
  "Phenazopyridine",
  "Propoxyphene",
  "Quinine",
  "Fadrozole",
  "Ketoconazole",
  "Tamoxifen",
  "Nevirapine",
  "Lamivudine",
  "Penciclovir",
  "Abacavir",
  "Alprazolam",
  "Desmethylvenlafaxine",
  "Nordiazepam",
  "Lorazepam-D4",
  "Oxazepam-d5",
  "Tamoxifen-d5",
  "Thiabendazole-d4",
  "Albuterol-d9",
  "Diltiazem-d3",
  "Trimethoprim-d9",
  "Acetaminophen-d3",
  "Norfluoxetine-d6",
  "Methadone-d9",
  "Oxycodone-d3",
  "Hydrocodone-d3",
  "Temazepam-d5",
  "Caffeine-trimethyl-13C3",
  "Sulfamethoxazole-13C6",
  "Cotinine-d3",
  "Amphetamine-d6",
  "Codeine-d6",
  "Pseudoephedrine-d3",
  "Diphenhydramine-d3",
  "Fluoxetine-d6",
  "Diazepam-D5",
  ".alpha.-Endosulfan",
  "Beta Cypermethrin",
  "Iprodione",
  ".lambda.-Cyhalothrin",
  "2-Ethyl-6-methylaniline",
  "3,4-Dichloroaniline",
  "3,5-Dichloroaniline",
  "4-Chloro-2-methylphenol",
  "Ethion monooxon",
  "Phosmetoxon",
  "cis-Propiconazole",
  "trans-Propiconazole",
  "Pymetrozine",
  "Silvex",
  "Propham",
  "Fenuron",
  "4,6-Dinitro-o-cresol",
  "Dichlorprop",
  "Chloramben methyl ester",
  "4-Bromo-3,5-dimethylphenyl N-Methylcarbamate",
  "Barban",
  "Cycloate",
  "Diphenamid",
  "2,4-D methyl ester",
  "3-Ketocarbofuran",
  "Bendiocarb",
  "Benomyl",
  "N-(4-Chlorophenyl)-N'-methylurea",
  "Bensulfuron-methyl",
  "Metsulfuron-methyl",
  "Caffeine-13C",
  "Fonofos oxon",
  "2-[2-[4-(1,1,3,3-Tetramethylbutyl)phenoxy]ethoxy]ethanol",
  "2-[4-(1,1,3,3-Tetramethylbutyl)phenoxy]ethanol",
  "Coprosterol",
  "3-Methylindole",
  "Phenol, 2-(1,1-dimethylethyl)-4-methoxy-",
  "p-Cumylphenol",
  "p-Octylphenol",
  "p-(1,1,3,3-Tetramethylbutyl)phenol",
  "5-Tolyltriazole",
  "AHTN",
  "Anthraquinone",
  "Benzophenone",
  ".beta.-Sitosterol",
  "4,4'-Isopropylidenediphenol",
  "Camphor",
  "Cholesterol",
  "D-Limonene",
  "1,3,4,6,7,8-Hexahydro-4,6,6,7,8,8-hexamethylcyclopenta[g]-2-benzopyran",
  "Indole",
  "Isoborneol",
  "Isoquinoline",
  "(1R,2S,5R)-Menthol",
  "Methyl salicylate",
  "N,N-Diethyl-m-toluamide",
  "Nonylphenol diethoxylate",
  "p-Cresol",
  "4-Nonylphenols",
  "Stigmastan-3.beta.-ol",
  "Tris(2-chloroethyl) phosphate",
  "Tris(1,3-dichloro-2-propyl)phosphate",
  "Tributyl phosphate",
  "Triclosan",
  "Triethyl citrate",
  "Triphenyl phosphate",
  "Tris(2-butoxyethyl) phosphate",
  "Caffeine-d9",
  "Bisphenol A-d14",
  "Decafluorobiphenyl",
  "Fluoranthene-d10",
  "Ethylan",
  "Chlorinated naphthalenes",
  "p,p'-DDD",
  "Polychlorinated biphenyls",
  "Aminomethylphosphonic acid",
  "Phytoplankton",
  "Ethinyl estradiol",
  "Estradiol",
  "Equilenin",
  "Estrone",
  "Bisphenol A-d3",
  "Carboxin",
  "Vernolate",
  "Simetryn",
  "Carbophenothion",
  "Carbophenothion-methyl",
  "Bis(2-chloroethyl) ether",
  "Bis(2-chloroisopropyl) ether",
  "N-Nitrosodi-n-propylamine",
  "p-Chloro-m-cresol",
  "o-Chlorophenol",
  "o-Nitrophenol",
  "BDE-003",
  "p-Chlorophenyl phenyl ether",
  "p-Nitrophenol",
  "Di(2-ethoxylhexyl) phthalate",
  "Dibutyl phthalate",
  "Cyanide",
  "Oxazepam",
  "Lorazepam",
  ".delta.-Hexachlorocyclohexane",
  "2,3,7,8,-Tetrachlorodibenzo-p-dioxin",
  ".beta.-Hexachlorocyclohexane",
  ".beta.-Endosulfan",
  "11-KetoTestosterone",
  "17.alpha.-Estradiol",
  "4-Androstenedione",
  "Androsterone",
  "trans-Diethylstilbestrol",
  "Epitestosterone",
  "Equilin",
  "Estriol",
  "Mestranol",
  "Progesterone",
  "5a-Dihydrotestosterone",
  "Testosterone",
  "2-NITROPHENOL",
  "2,4,5-TRICHLOROPHENOL",
  "2,4,6-TRICHLOROPHENOL",
  "2,4-DICHLOROPHENOL",
  "2,4-DIMETHYLPHENOL",
  "2,4-DINITROPHENOL",
  "2,4-DINITROTOLUENE",
  "2,6-DINITROTOLUENE",
  "2-CHLOROPHENOL",
  "2-METHYLPHENOL",
  "2-NITROANILINE",
  "3,3'-DICHLOROBENZIDINE",
  "4-CHLORO-3-METHYLPHENOL",
  "4,6-DINITRO-2-METHYLPHENOL",
  "4-NITROPHENOL",
  "PENTACHLOROPHENOL",
  "PHENOL",
  "3-NITROANILINE",
  "4-BROMOPHENYL PHENYL ETHER",
  "4-CHLOROANILINE",
  "4-CHLOROPHENYL PHENYL ETHER",
  "4-METHYLPHENOL",
  "4-NITROANILINE",
  "BENZOIC ACID",
  "BENZYL ALCOHOL",
  "bis(2-CHLOROETHOXY)METHANE",
  "bis(2-CHLOROETHYL)ETHER",
  "bis(2-ETHYLHEXYL)PHTHALATE",
  "BUTYL BENZYL PHTHALATE",
  "ACETOPHENONE",
  "ATRAZINE",
  "BENZIDINE",
  "bis(2-CHLOROISOPROPYL)ETHER",
  "CAPROLACTAM",
  "CARBAZOLE",
  "DIBENZOFURAN",
  "DIETHYL PHTHALATE",
  "DIMETHYL PHTHALATE",
  "DI-n-BUTYL PHTHALATE",
  "DI-n-OCTYL PHTHALATE",
  "HEXACHLOROBENZENE",
  "HEXACHLOROCYCLOPENTADIENE",
  "HEXACHLOROETHANE",
  "METHYLPHENOL ISOMERS SUM",
  "NITROBENZENE",
  "N-NITROSO-di-n-PROPYLAMINE",
  "N-NITROSODIPHENYLAMINE",
  "2,3,4,6-TETRACHLOROPHENOL",
  "3-methylphenol",
  "ANILINE",
  "AZOBENZENE",
  "N-NITROSODIMETHYLAMINE",
  "PYRIDINE",
  "methylene blue active substances",
  "4,4'-DDD",
  "4,4'-DDE",
  "Alachlor",
  "ALDICARB",
  "ALDRIN",
  "METHYL AZINPHOS",
  "BENEFIN",
  "CARBOFURAN",
  "CHLORPYRIFOS",
  "CYANAZINE",
  "chlorothalonil",
  "DCPA (dacthal)",
  "4,4'-DDT",
  "DIAZINON",
  "DIELDRIN",
  "ENDOSULFAN I",
  "ENDOSULFAN II",
  "ENDRIN",
  "EPTAM",
  "HEPTACHLOR EPOXIDE",
  "HEPTACHLOR",
  "HEXAZINONE",
  "GAMMA-BHC (LINDANE)",
  "METHOXYCHLOR",
  "METHYL PARATHION",
  "Pemethrin, mixed isomers",
  "trifluralin",
  "PICLORAM",
  "PROPACHLOR",
  "PROPOXUR",
  "SIMAZINE",
  "TOXAPHENE",
  "DIETHYL ETHER",
  "ACETATE ION",
  "n-BUTANOATE",
  "ETHYLENE GLYCOL",
  "HEXANAL",
  "OCTANAL",
  "PROPYLENE GLYCOL",
  "TETRAETHYLENE GLYCOL",
  "TRIETHYLENE GLYCOL",
  "METHANOL",
  "DIETHYLENE GLYCOL",
  "3-HYDROXYCARBOFURAN",
  "1-NAPHTHYLAMINE",
  "2-NAPHTHYLAMINE",
  "1,2,4,5-TETRACHLOROBENZENE",
  "2,6-DICHLOROPHENOL",
  "2-PICOLINE",
  "4-AMINOBIPHENYL",
  "ALDICARB SULFONE",
  "ALDICARB SULFOXIDE",
  "Aroclor 1016",
  "AROCLOR 1221",
  "AROCLOR 1232",
  "Aroclor 1242",
  "Aroclor 1248",
  "AROCLOR 1254",
  "AROCLOR 1260",
  "BUTACHLOR",
  "CARBARYL",
  "DALAPON",
  "DICAMBA",
  "DINOSEB",
  "DIQUAT",
  "GLYPHOSATE",
  "METHIOCARB",
  "METHOMYL",
  "METOLACHLOR",
  "METRIBUZIN",
  "OXAMYL",
  "N-NITROSODI-n-BUTYLAMINE",
  "SAFROLE",
  "1,3,5-TRINITROBENZENE",
  "5-NITRO-O-TOLUIDINE",
  "PRONAMIDE",
  "ISODRIN",
  "CHLOROBENZILATE",
  "4-DIMETHYLAMINOAZOBENZENE",
  "PENTACHLOROBENZENE",
  "PHENACETIN",
  "ETHYL METHANESULFONATE",
  "METHYL METHANESULFONATE",
  "PENTACHLORONITROBENZENE",
  "ISOSAFROLE",
  "DIPHENYLAMINE",
  "alpha-Chlordane",
  "Aroclor 1268",
  "Arolcor 1262",
  "beta-BHC",
  "CHLORDANE, technical",
  "delta-BHC",
  "ENDOSULFAN SULFATE",
  "ENDRIN ALDEHYDE",
  "ENDRIN KETONE",
  "GAMMA-CHLORDANE",
  "Kepone",
  "Mirex",
  "2,4'-DDD",
  "2,4'-DDE",
  "2,4'-DDT",
  "1,3-DINITROBENZENE",
  "1,4-DINITROBENZENE",
  "2,4,6-TRINITROTOLUENE",
  "2-AMINO-4,6-DINITROTOLUENE",
  "2-NITROTOLUENE",
  "3-NITROTOLUENE",
  "4-AMINO-2,6-DINITROTOLUNENE",
  "4-NITROTOLUENE",
  "HMX",
  "RDX",
  "TETRYL",
  "BUTYLATED HYDROXYTOLUENE",
  "2,5-DIBROMOTOLUENE",
  "3-Phenoxybenzoic acid",
  "Optical Brightener",
  "Caffeine",
  "isohexanoic acid",
  "2,3,5,6-tetrachlorophenol",
  "Squalene",
  "Terpiniol",
  "tri-(2-butoxyethyl) phosphate",
  "bis(2-ETHYLHEXYL) ADIPATE",
  "R-(+)-limonene",
  "1,2-dinitrobenzene",
  "1,3-dimethyladamantane",
  "Adamantane",
  "PHORATE",
  "4,4'-METHYLENE-bis(2-CHLOROANILINE)",
  "SILVEX (2,4,5-TP)",
  "2,4-DICHLOROPHENOXYACETIC ACID",
  "POLYCHLORINATED BIPHENYLS, N.O.S.",
  "ENDOTHAL",
  "2,4,5-T",
  "2,4-DB",
  "2,4-DP",
  "2,6-Diethylaniline",
  "Acifluorfen",
  "Alpha BHC",
  "Ametryn",
  "Azinphos methyl",
  "Azinphos methyl oxon",
  "Benfluralin",
  "Bensulfuron methyl",
  "Benzovindiflupyr",
  "Bicyclopyrone",
  "Bifenthrin",
  "Boscalid",
  "Bromoxynil",
  "Butylate",
  "Captan",
  "Carfentrazone ethyl",
  "Chloransulam methyl",
  "Chlorimuron ethyl",
  "Chlorpyrifos OA",
  "Chlorpyrifos methyl",
  "Clodinafop",
  "Cyfluthrin",
  "Cypermethrin",
  "Cyproconazole",
  "Cyprodinil",
  "DDD",
  "DDE",
  "Dichlobenil",
  "Difenoconazole",
  "Diflubenzuron",
  "Disulfoton sulfone",
  "Disulfoton sulfoxide",
  "EPTC",
  "Endosulfan alpha",
  "Endosulfan beta",
  "Epoxiconazole",
  "Esfenvalerate",
  "Ethalfluralin",
  "Ethion",
  "Ethofumesate",
  "Fenamiphos sulfoxide",
  "Fenbuconazole",
  "Fipronil",
  "Florasulam",
  "Flucarbazone",
  "Flucarbazone sulfonamide",
  "Fludioxonil",
  "Flufenacet",
  "Flufenacet OA",
  "Flumetsulam",
  "Fluopyram",
  "Fonofos",
  "Glufosinate",
  "Glutamic acid",
  "Halofenozide",
  "Halosulfuron methyl",
  "Hydroxy Simazine",
  "Imazalil",
  "Imazamethabenz methyl ester",
  "Imazaquin",
  "Iodosulfuron methyl sodium",
  "Isofenphos",
  "Isoxaflutole",
  "Kresoxim methyl",
  "Lambda Cyhalothrin",
  "MCPB",
  "Malathion OA",
  "Mesotrione",
  "Metconazole",
  "Methidathion",
  "Methoxyfenozide",
  "Molinate",
  "Monuron",
  "Myclobutanil",
  "NOA 407854",
  "NOA 447204",
  "Napropamide",
  "Neburon",
  "Norflurazon desmethyl",
  "Oxyfluorfen",
  "Parathion ethyl",
  "Parathion ethyl OA",
  "Parathion methyl",
  "Pebulate",
  "Pendimethalin",
  "Permethrin",
  "Phorate OA",
  "Phorate sulfone",
  "Phorate sulfoxide",
  "Phosmet",
  "Phosmet OA",
  "Prallethrin",
  "Profenofos",
  "Prometryn",
  "Propachlor OA",
  "Propanil",
  "Propargite",
  "Propiconazole",
  "Propyzamide",
  "Prosulfuron",
  "Prothioconazole",
  "Pyraclostrobin",
  "Pyrasulfotole",
  "Pyrimethanil",
  "Pyroxsulam",
  "Resmethrin",
  "Sulfometuron methyl",
  "Sulfosulfuron",
  "Sulprofos",
  "Tebuconazole",
  "Tebufenozide",
  "Tefluthrin",
  "Tembotrione",
  "Terbacil",
  "Terbufos",
  "Terbufos OA",
  "Terbufos sulfone",
  "Terbuthylazine",
  "Tetrachlorvinphos",
  "Tetradifon",
  "Tetramethrin",
  "Thiencarbazone methyl",
  "Thifensulfuron",
  "Thiobencarb",
  "Tolfenpyrad",
  "Tralkoxydim",
  "Tralkoxydim acid",
  "Tralomethrin",
  "Triadimefon",
  "Triadimenol",
  "Triallate",
  "Triasulfuron",
  "Trichlorfon",
  "Triticonazole",
  "Vinclozolin",
  "o,p'-DDE",
  "p,p'-DDE",
  "p,p'-DDT",
  "DOC - Dissolved Organic Carbon",
  "Triazine (ELISA)",
  "Metolachlor ESA",
  "Metolachlor OA",
  "Clothianidin",
  "Desethyl Atrazine",
  "Hydroxy Atrazine",
  "Imazapyr",
  "Alachlor ESA",
  "Prometon",
  "Thiamethoxam",
  "Phosphamidon",
  "Desisopropyl Atrazine",
  "Chlorantraniliprole",
  "Bromacil",
  "Dimethenamid ESA",
  "Imazamethabenz acid",
  "Tebuthiuron",
  "Imidacloprid",
  "2,4-D",
  "Acetochlor ESA",
  "Diuron",
  "Fluroxypyr",
  "Diflufenzopyr",
  "Metalaxyl",
  "Dimethenamid OA",
  "Clopyralid",
  "Imazapic",
  "Chlorsulfuron",
  "Tetraconazole",
  "Alachlor OA",
  "Imazamox",
  "Propazine",
  "Imazethapyr",
  "Sulfentrazone",
  "Aminopyralid",
  "Dimethoate",
  "Azoxystrobin",
  "Nicosulfuron",
  "MCPP",
  "AMPA",
  "Lindane",
  "DCPA",
  "Quinclorac",
  "Carbendazim",
  "Flubendiamide",
  "Desethyl Hydroxy Atrazine",
  "Bentazon",
  "Diazinon OA",
  "Acetochlor",
  "Dinotefuran",
  "Cyromazine",
  "Acetochlor OA",
  "Dichlorvos",
  "Metsulfuron methyl",
  "Malathion",
  "Oxydemeton methyl",
  "Fenamiphos sulfone",
  "Ethoprop",
  "MCPA",
  "Norflurazon",
  "Fenamiphos",
  "Dimethenamid",
  "Linuron",
  "Triclopyr",
  "2-Chloro-4-isopropylamino-6-amino-s-triazine",
  ".alpha.-Hexachlorocyclohexane",
  "gamma-HCH (Lindane)",
  "Parathion",
  "S-Ethyl dipropylthiocarbamate",
  "Chlorthal-dimethyl",
  "Azinphos-methyl",
  "1rs Cis-Permethrin",
  "Diazinon-D10",
  ".alpha.-1,2,3,4,5,6-Hexachlorocyclohexane-D6 or alpha-HCH D6",
  "Perchlorate",
  "Piperonyl butoxide",
  "Fipronil Desulfinyl",
  "Fipronil Sulfide",
  "Fipronil Sulfone",
  "Trifloxystrobin",
  "Bisphenol A-d16",
  "Famoxadone",
  "Kresoxim-methyl",
  "1-Methoxy-4-(2-propenyl)benzene",
  "Azinphos-methyl oxygen analog",
  "Chlorpyrifos O.A.",
  "3,4-Dichlorophenylurea",
  "1-(3,4-dichlorophenyl)-3-methyl urea",
  "Diazoxon",
  "Malaoxon",
  "4-Hydroxychlorothalonil",
  "1H-1,2,4-Triazole",
  "2-Aminobenzimidazole",
  "Benzamide, 2-amino-N-(1-methylethyl)-",
  "2-Isopropyl-6-methyl-4-pyrimidinol",
  "4-(Hydroxymethyl) pendimethalin",
  "4-Chlorobenzyl methyl sulfoxide",
  "4-Hydroxy molinate",
  "4-Hydroxyhexazinone A",
  "Acephate",
  "2-Chloro-N-(2-ethyl-6-methylphenyl)acetamide",
  "Acetochlor sulfinylacetic acid",
  "2-Chloro-2',6'-diethylacetanilide",
  "Alachlor sulfinylacetic acid",
  "Asulam",
  "Butralin",
  "2-Chloro-4,6-diamino-s-triazine",
  "Carboxy molinate",
  "Chlorosulfonamide acid",
  "cis-Cyhalothric acid",
  "Chlorthal-Monomethyl",
  "Dechlorofipronil",
  "Dechlorometolachlor",
  "Deiodo flubendiamide",
  "Deisopropyl prometryn",
  "Demethyl hexazinone B",
  "Desmethylnorflurazon",
  "Metribuzin DA",
  "Metribuzin DADK",
  "Desulfinylfipronil amide",
  "Dicrotophos",
  "Didemethyl hexazinone F",
  "Tebuthiuron TP 104",
  "Benzenepropanenitrile, .alpha.-(cyclopropylcarbonyl)- 2-(methylsulfonyl)-.beta.- oxo-4-(trifluoromethyl)-",
  "Dimethenamid oxanilic acid",
  "Dimethenamid sulfinylacetic acid",
  "Demeton-S",
  "Disulfoton oxon sulfoxide",
  "Disulfoton oxon sulfone",
  "Oxydisulfoton",
  "Demethylfluometuron",
  "EPTC degradate R248722",
  "2-[(2-Ethyl-6-methylphenyl)-amino]-1-propanol",
  "O-Ethyl O-methyl S-propyl phosphorothioate",
  "Etoxazole",
  "Fenbutatin-oxide",
  "Fentin",
  "1H-Pyrazole-3-carboxamide, 5-amino-1-[2,6-dichloro-4-(trifluoromethyl)phenyl]-4-[(trifluoromethyl)sulfinyl]-",
  "Fipronil sulfonate",
  "1,2-Benzenedicarboxamide, N2-[1,1-dimethyl-2-(methylsulfonyl)ethyl]-3-iodo-N1-[2-methyl-4-[1,2,2,2-tetrafluoro-1-(trifluoromethyl)ethyl]phenyl]-",
  "Fluometuron",
  "2-(1-Hydroxyethyl)-6-methylaniline",
  "Hexazinone Transformation Product C",
  "Hexazinone Transformation Product D",
  "Hexazinone Transformation Product E",
  "Hydroxysimazine",
  "Hydroxyacetochlor",
  "Hydroxyalachlor",
  "Hydroxy monodemethyl fluometuron",
  "Hydroxydiazinon",
  "Hydroxy didemethyl fluometuron",
  "Hydroxyfluometuron",
  "Hydroxytebuthiuron",
  "Hydroxymetolachlor",
  "Hydroxyphthalazinone",
  "Indoxacarb",
  "Isoxaflutole acid metabolite RPA 203328",
  "Lactofen",
  "Methamidophos",
  "Ethanimidothioic acid, N-hydroxy-, methyl ester",
  "Methyl paraoxon",
  "Metolachlor hydroxy morpholinone",
  "Metochlor ESA",
  "Metribuzin DK",
  "Naled",
  "Novaluron",
  "Deisopropylhydroxyatrazine",
  "O-Ethyl S-methyl S-propyl phosphorodithioate",
  "O-Ethyl S-propyl phosphorothioate",
  "Deethylhydroxyatrazine",
  "2-Hydroxyatrazine",
  "Omethoate",
  "Orthosulfamuron",
  "Oryzalin",
  "2-(Dimethylamino)-N-hydroxy-2-oxoethanimidothioic acid methyl ester",
  "Paraoxon",
  "Phorate O.A.",
  "Phorate oxygen analog sulfone",
  "Phorate oxon sulfoxide",
  "Phthalazinone",
  "Pyridaben",
  "Pyriproxyfen",
  "sec-Acetochlor oxanilic acid",
  "sec-Alachlor oxanilic acid",
  "Siduron",
  "Sulfosulfuron ethyl sulfone",
  "2,3,3-Trichloro-2-propene-1-sulfonic acid (sodium salt)",
  "Phostebupirim",
  "Tebupirimphos oxon",
  "Tebuthiuron Transformation Product 108",
  "Tebuthiuron TP 109 (OH)",
  "Terbufos oxon",
  "Terbufos oxygen analog sulfone",
  "Terbufos oxon sulfoxide",
  "Terbufos sulfoxide",
  "Transpermethrin",
  "Tribufos",
  "Hexazinone Transformation Product G",
  "Tebuthiuron TP 106",
  "3-Phenoxybenzoic acid",
  "Sulfite",
  "N-NITROSOPIPERIDINE",
  "PROPANOIC ACID, ION",
  "CAPROIC ACID ION",
  "FORMIC ACID",
  "LACTIC ACID",
  "PROPANOIC ACID",
  "n-BUTANOIC ACID",
  "2-METHYLPROPANOIC ACID, ion",
  "3-METHYL-BUTANOIC ACID ION",
  "PENTANOIC ACID, ion",
  "ACETIC ACID",
  "PYRUVIC ACID",
  "3-methylbutanoic acid",
  "isoohexanoic acid",
  "hexanoic acid",
  "1-Naphthol",
  "Phenols",
  "2-Nitroaniline",
  "3-Nitroaniline",
  "4-Nitroaniline",
  "4-Chlorophenyl Phenyl Ether",
  "bis(2-Ethylhexyl)phthalate",
  "Di-n-octyl phthalate",
  "Benzoic Acid",
  "Acetonitrile",
  "Allyl alcohol",
  "Butyl benzyl phthalate",
  "Diethyl phthalate",
  "Dimethyl phthalate",
  "Aniline",
  "Azobenzene",
  "Isophorone",
  "Nitrobenzene",
  "Pyridine",
  "Benzaldehyde",
  "Acetophenone",
  "Benzidine"
)













Metals_and_Elements <- c("Sulfate", "Cesium",
  "cesium",
  "Arsenite",
  "Arsenate",
  "Monomethylarsonate",
  "Cacodylic acid",
  "U (Total) - Uranium Total",
  "U - Uranium",
  "SULFIDE as H2S",
  "SILICA (SiO2)",
  "Silicon Dioxide",
  "Sodium plus potassium",
  "Bismuth",
  "Tin",
  "Cerium",
  "Gallium",
  "Titanium",
  "Tungsten",
  "Lanthanum",
  "Ytterbium",
  "Yttrium",
  "Erbium",
  "Europium",
  "Gadolinium",
  "Holmium",
  "Neodymium",
  "Praseodymium",
  "Terbium",
  "Thulium",
  "Sulfur",
  "Lutetium",
  "Samarium",
  "Dysprosium",
  "Germanium",
  "Zirconium",
  "Scandium",
  "Hafnium",
  "Niobium",
  "Rhenium",
  "Tellurium",
  "Indium",
  "Tantalum",
  "Gold",
  "Ferrous ion",
  "Iron(II)/Iron(III)",
  "Chromium(VI)",
  "Methylmercury(1+)",
  "Sulfide",
  "Hydroxide",
  "Selenate",
  "Selenite",
  "Silicon",
  "BROMIDE",
  "SULFATE",
  "THORIUM",
  "SILICON (Si)",
  "Rubidium",
  "Na + K",
  "IRON II (FERROUS)",
  "PHOSPHATE",
  "As (Total) - Arsenic Total",
  "Ba (Total) - Barium Total",
  "Ca (Total) - Calcium Total",
  "Cr (Total) - Chromium Total",
  "Cu (Total) - Copper Total",
  "K (Total) - Potassium Total",
  "Mg (Total) - Magnesium Total",
  "Na (Total) - Sodium (Total)",
  "Na - Sodium",
  "Rb - Rubidium",
  "S (Total) - Sulfur Total",
  "SAR - Sodium Absorption Ratio",
  "Silica - Silica as SiO2",
  "Sr (Total) - Strontium Total",
  "Sr - Strontium",
  "Ti - Titanium",
  "Y - Yttrium",
  "SO4 - Sulfate",
  "Ca - Calcium",
  "HCO3 - Bicarbonate",
  "Mg - Magnesium",
  "Cl - Chloride",
  "Al (Total) - Aluminum Total",
  "K - Potassium",
  "F - Fluoride",
  "Zn (Total) - Zinc Total",
  "Li - Lithium",
  "Br - Bromide",
  "Co (Total) - Cobalt Total",
  "Cs - Caesium",
  "Sc - Scandium",
  "Ba - Barium",
  "Ni (Total) - Nickel Total",
  "Se (Total) - Selenium Total",
  "Pb (Total) - Lead Total",
  "B - Boron",
  "Mo (Total) - Molybdenum Total",
  "W (Total) - Tungsten Total",
  "Mn - Manganese",
  "Zn - Zinc",
  "Tl (Total) - Thallium Total",
  "Se (Dissolved) - Selenium Dissolved",
  "Fe - Iron",
  "Mo - Molybdenum",
  "Al - Aluminum",
  "Cr - Chromium",
  "Cu - Copper",
  "Ni - Nickel",
  "As - Arsenic",
  "V - Vanadium",
  "Co - Cobalt",
  "Sb - Antimony",
  "Cd (Total) - Cadmium Total",
  "Mn (Total) - Manganese Total",
  "Pb - Lead",
  "Cd - Cadmium",
  "Fe (Total) - Iron Total",
  "Be - Beryllium",
  "Sb (Total) - Antimony Total",
  "Tl - Thallium",
  "CO3 - Carbonate",
  "Ag - Silver",
  "Calcium",
  "Magnesium",
  "Sodium",
  "Potassium",
  "Chloride",
  "Fluoride",
  "Silica",
  "Arsenic",
  "Barium",
  "Cadmium",
  "Chromium",
  "Copper",
  "Iron",
  "Lead",
  "Manganese",
  "Thallium",
  "Nickel",
  "Strontium",
  "Zinc",
  "Antimony",
  "Aluminum",
  "Selenium",
  "Beryllium",
  "Cobalt",
  "Molybdenum",
  "Silver",
  "Vanadium",
  "Boron",
  "Lithium",
  "Mercury",
  "Sulfite",
  "Fentin",
  "Calcium Carbonate",
  "ANTIMONY",
  "ALUMINUM",
  "ARSENIC",
  "BARIUM",
  "BERYLLIUM",
  "BORON",
  "CADMIUM",
  "CALCIUM",
  "CHROMIUM",
  "CHROMIUM VI",
  "CHROMIUM III",
  "COBALT",
  "COPPER",
  "IRON",
  "IRON, FIELD",
  "LEAD",
  "LITHIUM",
  "MAGNESIUM",
  "MANGANESE",
  "MERCURY",
  "MOLYBDENUM",
  "NICKEL",
  "POTASSIUM",
  "SELENIUM",
  "SILVER",
  "STRONTIUM",
  "THALLIUM",
  "TIN",
  "TITANIUM",
  "TUNGSTEN",
  "URANIUM",
  "VANADIUM",
  "ZINC",
  "BISMUTH",
  "CERIUM",
  "GALLIUM",
  "GERMANIUM",
  "HAFNIUM",
  "NIOBIUM",
  "RHENIUM",
  "TELLURIUM",
  "INDIUM",
  "TANTALUM",
  "GOLD",
  "ZIRCONIUM",
  "YTTRIUM",
  "SCANDIUM",
  "EUROPIUM",
  "GADOLINIUM",
  "HOLMIUM",
  "LANTHANUM",
  "LUTETIUM",
  "NEODYMIUM",
  "PRASEODYMIUM",
  "SAMARIUM",
  "TERBIUM",
  "THULIUM",
  "YTTERBIUM",
  "DYSPROSIUM",
  "CESIUM",
  "IODIDE ION",
  "SULFUR",
  "SULFIDE",
  "CYANIDE",
  "CHLORIDE",
  "FLUORIDE",
  "CALCIUM",
  "POTASSIUM",
  "MAGNESIUM",
  "SODIUM",
  "IRON",
  "MANGANESE",
  "ZINC",
  "COPPER",
  "CHLORIDE AS NACL",
  "SULFATE as S"
)






PFAS <- c(
  "Perfluorobutanesulfonate",
  "Perfluoropentanesulfonate",
  "Perfluorohexanesulfonate",
  "Perfluoroheptanesulfonate",
  "Perfluorooctanesulfonate",
  "Perfluorononanesulfonate",
  "Perfluorodecanesulfonate",
  "Perfluorobutanoate",
  "Perfluoropentanoate",
  "Perfluorohexanoate",
  "Perfluoroheptanoate",
  "PFOA ion",
  "Perfluorononanoate",
  "Perfluorodecanoate",
  "Perfluoroundecanoate",
  "Perfluorododecanoate",
  "N-Methylperfluorooctanesulfonamidoacetate",
  "N-Ethylperfluorooctanesulfonamidoacetate",
  "Fluorotelomer sulfonate 4:2",
  "Fluorotelomer sulfonate 8:2",
  "Perfluorotridecanoate",
  "Perfluorotetradecanoate",
  "Fluorotelomer sulphonic acid 4:2",
  "Fluorotelomer sulphonic acid 6:2",
  "Fluorotelomer sulphonic acid 8:2",
  "Hexafluoropropylene oxide dimer acid",
  "N-Ethyl perfluorooctanesulfonamidoacetic acid",
  "N-methylperfluorooctane sulfonamidoacetic acid",
  "Perfluorobutanoic acid",
  "Perfluorodecanesulfonic acid",
  "Perfluoroheptane sulfonate",
  "Perfluorononanesulfonic acid",
  "Perfluorooctanesulfonamide",
  "Perfluoropentanoic acid",
  "Perfluoropentanesulfonic acid",
  "Perfluorobutanesulfonic acid",
  "Perfluorodecanoic acid",
  "Perfluorododecanoic acid",
  "Perfluoroheptanoic Acid",
  "Perfluorohexanesulfonic acid",
  "Perfluorohexanoic acid",
  "Perfluorononanoic acid",
  "Perfluorooctanesulfonic acid",
  "Perfluorooctanoic acid",
  "Perfluorotetradecanoic acid",
  "Perfluorotridecanoic acid",
  "Perfluoroundecanoic acid",
  "1-Octanesulfonic acid, 3,3,4,4,5,5,6,6,7,7,8,8,8-tridecafluoro-",
  "Perfluoro(2-propoxypropanoate)",
  "4,8-dioxa-3H-perfluorononanoate",
  "9-Chlorohexadecafluoro-3-oxanonane-1-sulfonate",
  "Perfluorobutylsulfonamide",
  "Perfluorohexanesulfonamide",
  "N-methylperfluoro-1-octanesulfonamide",
  "N-ethyl Perfluorooctane sulfonamide",
  "11-chloroeicosafluoro-3-oxaundecane-1-sulfonate"
)



Nitrogen <- c(
  "Inorganic nitrogen (nitrate and nitrite)",
  "Inorganic nitrogen (nitrate and nitrite) retireduse Nitrate + Nitrite",
  "Inorganic nitrogen (nitrate and nitrite) retireduse Nitrate + Nitrite",
  "Nitrate + Nitrite",
  "Total Kjeldahl nitrogen (Organic N & NH3)",
  "Inorganic nitrogen (nitrate and nitrite) retireduse Nitrate + Nitrite",
  "Nitrite as NO2",
  "InorganicN - Inorganic N (NO3-N + NO2-N)",
  "NO3N - Nitrate as Nitrogen (NO3-N)",
  "TN_Kjeldahl - Total Kjeldahl Nitrogen",
  "NH3N - Ammonia (un-ionized) as Nitrogen",
  "NO2N - Nitrite as Nitrogen (NO2-N)",
  "Nitrogen, mixed forms (NH3), (NH4), organic, (NO2) and (NO3)",
  "Organic Nitrogen",
  "Nitrite",
  "Nitrate",
  "Kjeldahl nitrogen",
  "Ammonia and ammonium",
  "AMMONIA",
  "AMMONIA AS N",
  "NITRATE",
  "NITRATE/NITRITE",
  "NITRATE/NITRITE AS N",
  "NITRATE as Nitrogen",
  "NITRITE",
  "NITRITE AS NO2",
  "NITRITE AS N",
  "TOTAL KJELDAHL NITROGEN",
  "INORGANIC N (NO3-N + NO2-N)",
  "TOTAL KJELDAHL NITROGEN",
  "ORGANIC NITROGEN",
  "AMMONIUM",
  "NITRATE AS N",
  "NITRITE AS N",
  "NITROGEN, MIXED FORMS",
  "KJELDAHL NITROGEN"
)


Phosphorus <- c(
  "Hydrolyzable phosphorus",
  "Organic phosphorus",
  "Total Phosphorus, mixed forms",
  "PHOSPHATE",
  "Orthophosphate_P - Dissolved Orthophosphate as P",
  "TP_Color - Total Phosphorus Color",
  "TSP_Color - Total Soluble Phosphorus Color",
  "TSP_ICP - Total Soluble Phosphorus ICP",
  "Phosphorus",
  "Orthophosphate",
  "Phosphate-phosphorus",
  "PHOSPHORUS",
  "ORTHOPHOSPHATE",
  "ORTHOPHOSPHATE AS P",
  "PHOSPHORUS, Total as PO4",
  "TP_Color",
  "TSP_Color",
  "TSP_ICP"
)

Carbon <- c(
  "Alkalinity_CaCO3 - Alkalinity (CaCO3)",
  "Bicarbonate",
  "Inorganic carbon",
  "TOTAL ORGANIC CARBON",
  "DOC - Dissolved Organic Carbon",
  "Organic carbon",
  "Total Organic Carbon",
  "Dissolved Organic Carbon",
  "Organic Carbon, Dissolved",
  "Inorganic Carbon, Dissolved",
  "Inorganic Carbon",
  "Carbonate as CaCO3",
  "Carbonate",
  "Total Kjeldahl nitrogen",
  "Organic Carbon"
)



Radionuclides <- c(
  "Beta particle",
  "Alpha particle",
  "Iodide",
  "BETA PARTICLE",
  "ALPHA PARTICLE",
  "URANIUM",
  "IODINE",
  "Potassium-40",
  "222Radon",
  "182TANTALUM",
  "Radium-226",
  "Uranium-234",
  "Uranium-235",
  "Radium-228",
  "Uranium",
  "Radium-224",
  "Carbon-14",
  "Tritium",
  "Lead-210",
  "Polonium-210",
  "GROSS ALPHA",
  "GROSS BETA",
  "RADON",
  "TRITIUM",
  "TRITIUM IN WATER",
  "214BISMUTH",
  "214LEAD",
  "226RADIUM",
  "228RADIUM",
  "210LEAD",
  "137Cesium",
  "59IRON",
  "208TITANIUM",
  "212LEAD",
  "210Polonium",
  "224Radium isotope",
  "14C IN DISSOLVED INORGANIC CARBON",
  "14C dissolved inorganic carbon age",
  "Radium 226 + Radium 228",
  "228ACTINIUM",
  "241Americium",
  "212BISMUTH",
  "60Cobalt",
  "40POTASSIUM",
  "234PROTACTINIUM, METASTABLE",
  "234THORIUM",
  "235URANIUM",
  "234URANIUM",
  "238Uranium",
  "Plutonium-238",
  "Plutonium-239 and Plutonium-240 combined",
  "Selenium-75",
  "Strontium-90",
  "Uranium-238/uranium-235",
  "Uranium 238/234 ratio",
  "Thorium-230",
  "Thorium-232",
  "Radon-222",
  "Alpha emitting radium isotopes"
)


Isotopic_Ratios <- c(
  "Carbon, isotope of mass 13",
  "DELTA 13C CO2",
  "HELIUM DILUTION FACTOR",
  "OXYGEN/ARGON RATIO",
  "Delta 13C iC5",
  "Delta 13C nC5",
  "OXYGEN + ARGON",
  "DELTA 18O H2O",
  "DELTA 13C C2",
  "DELTA 13C C3",
  "DELTA 13C DIC",
  "DELTA D H2O",
  "DELTA 13C C1",
  "DELTA D C1",
  "DELTA 87Sr/86Sr",
  "DELTA D C2",
  "DELTA 15N N2",
  "DELTA 18O CO2",
  "DELTA 13C iC4",
  "DELTA 13C nC4",
  "delta34S_sulfate",
  "delta18O_sulfate",
  "DELTA D nC4",
  "DELTA 13C iC5",
  "DELTA 13C nC5",
  "Carbon-13/Carbon-12 ratio",
  "Deuterium/Hydrogen ratio",
  "Oxygen-18/Oxygen-16 ratio",
  "Sulfur-34/Sulfur-32 ratio",
  "Nitrogen-15/14 ratio",
  "Strontium-87/Strontium-86, ratio",
  "Lead-206/lead-204",
  "Lead-207/lead-204",
  "Lead-208/lead-204"
)


#### Assigning analyte categories #####

# Create a variable that identifies when an analyte is physical versus contaminant
GW_Merged4 <- GW_Merged3 |>
  mutate(
    Analyte_Sub_Category = case_when(
      Analyte %in% Physical_Parameters ~ "Physical Parameters",
      Analyte %in% Gases ~ "Gases",
      Analyte %in% VOCs ~ "Volatile Organic Compounds (VOCs)",
      Analyte %in% PAHs ~ "Polycyclic Aromatic Hydrocarbons (PAHs)",
      Analyte %in% Fuels_Hydrocarbon_Mixtures ~ "Fuels and Hydrocarbon Mixtures",
      Analyte %in% Other_Organics ~ "Other Organics",
      Analyte %in% Metals_and_Elements ~ "Metals and Other Elements",
      Analyte %in% PFAS ~ "PFAS",
      Analyte %in% Nitrogen ~ "Nitrogen",
      Analyte %in% Phosphorus ~ "Phosphorus",
      Analyte %in% Carbon ~ "Carbon",
      Analyte %in% Radionuclides ~ "Radionuclides",
      Analyte %in% Isotopic_Ratios ~ "Isotopic Ratios",
      TRUE ~ "Other Analytes"
    )
  )

GW_Merged_5 <- GW_Merged4 |>
  mutate(
    Analyte_Category = case_when(
      Analyte_Sub_Category %in% c("Physical Parameters", "Gases") ~ "Physical Water Properties",
      Analyte_Sub_Category %in% c(
        "Volatile Organic Compounds (VOCs)",
        "Polycyclic Aromatic Hydrocarbons (PAHs)",
        "Fuels and Hydrocarbon Mixtures",
        "Other Organics"
      ) ~ "Organic Contaminants",
      Analyte_Sub_Category %in% c("Metals and Other Elements", "PFAS") ~ "Non-Organic Contaminants",
      Analyte_Sub_Category %in% c("Nitrogen", "Phosphorus", "Carbon") ~ "Nutrients",
      Analyte_Sub_Category %in% c("Radionuclides", "Isotopic Ratios") ~ "Radiochemical",
      TRUE ~ "Other Analytes" # Catch-all for main category
    )
  )


##### Subsetting data into different category datasets

GW_Merged_6 <- GW_Merged5 |>  filter(Analyte_Sub_Category != "Physical Parameters")



unique(Other_Analytes3)
# Export to CSV because excel doesn't work for over 1 million observations
write.csv(Other_Analytes2,
          "02_Raw_Data/Other_Analytes2.csv",
          row.names = FALSE)


# Keep rows where AnalyteType is not 'Physical' OR where AnalyteType is NA.

GW_MERGED_INTERMEDIATE <- GW_Merged3 |>
  filter(AnalyteType != "Physical" | is.na(AnalyteType))


unique(GW_MERGED_INTERMEDIATE$AnalyteType)


# Create a vector to identify all the different analyte types
Analytes <- GW_MERGED_INTERMEDIATE |>  select(Analyte, Source)

Analytes_1 <- unique(Analytes)







# Export to CSV to review analytes
write.csv(Analytes_1, "02_Raw_Data/Analytes.csv", row.names = FALSE)

# Export to CSV because excel doesn't work for over 1 million observations
write.csv(GW_MERGED_INTERMEDIATE,
          "02_Raw_Data/GW_Contaminants_Merged.csv",
          row.names = FALSE)




#### Summarizing the Data ####

GW_Merged3 <- GW_Merged3 |>  mutate


DF <- DF |>
  # 1. Group the data by both 'Analyte' and 'County'
  group_by(Analyte, County) |>
  # 2. Calculate the desired summary statistics for each group
  summarise(
    Mean_Value = mean(YourMeasurementColumn, na.rm = TRUE),
    Median_Value = median(YourMeasurementColumn, na.rm = TRUE),
    Min_Value = min(YourMeasurementColumn, na.rm = TRUE),
    Max_Value = max(YourMeasurementColumn, na.rm = TRUE),
    SD_Value = sd(YourMeasurementColumn, na.rm = TRUE),
    N_Observations = n(),
    # Count the number of observations in each group
    .groups = 'drop' # This removes the grouping structure after summarising
  )
